const help8 = (prefix) => {

	return `

OLÁÁ, ${pushname}, SEJA BEM VINDO AO MENU DE INFORMAÇÕES SOBRE O BOT 


═════════════════
__| ☾ * LEAL BOT * 🪐 ☽ 

ENTÃO, SENHOR(A) ${pushname}, AQUI ESTÃO AS INFORMAÇÕES ⤵️

DONO: KAUA SHELBY
CRIADOR:MURILOO.mp4 

A CRIAÇÃO DESSE BOT, FOI INSPIRADA NA SONAR BOT 

SOBRE O DONO:

REDES SOCIAIS ⤵️

INSTAGRAM: @muriloo.mp4 
WPP: wa.me/555597294998 

COMPRAS: 

COMPRE SEU BOT ⤵️

ARQUIVO DO BOT PRONTO, TOTALMENTE EDITÁVEL (APENAS PARA PC) E COM ATUALIZAÇÕES
↪️R$30,00↩️

BOT COM O NOME QUE QUISER, COM UM NÚMERO PRÓPRIO CRIADO PELO MURILOO, E ON NOS HORÁRIOS QUE VOCÊ PREFERIR:
↪️R$15,00↩️

PREMIUM NO BOT DO MURILOO: 
↪️R$2,50↩️

PERMISSÃO PARA ADICIONAR OS BOTS DO MURILOO EM QUALQUER GRUPO:
↪️R$5,00↩️

DÚVIDAS, CHAME O CRIADOR DO BOT NO WPP: wa.me/555597294998 

MUITO OBRIGADO, ${pushname}, POR USAR O LEAL BOT, APROVEITE O BOT, E POR FAVOR, NÃO FLODE O CHAT 


╰╼  *LEAL*🪐

`
}
exports.help8 = help8

